name: image_build_dev
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 2 * * *'

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        DEVICE: [pinephone,pinephonepro]
        EDITION: [plasma-mobile-dev]
        BRANCH: [unstable]
    steps:
      -
        id: time
        uses: boredland/get-time-action@2.0.0
        with:
          format: 'YYYYMMDDHHmm'
      -
        id: image-build
        uses: manjaro-arm/rootfs@master
        with:
          overlay-repo: kde-unstable
          device: ${{ matrix.device }}
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          version: ${{ steps.time.outputs.time }}
          #gpg-key: ${{ secrets.CI_GPG_SECRET }}
          #gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
      -
        name: Release assets
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          name: Developer Release ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
          files: |
            ${{ env.FILE_PATH }}
            ${{ env.FILE_SHA1 }}
            ${{ env.FILE_TORRENT }}
            ${{ env.FILE_PKG }}
            #${{ env.FILE_SIG }}
